require('dotenv').config();
const mongoose = require('mongoose');
const User = require('./models/user.model');
const Interest = require('./models/interest.model');

const seedProfiles = [
  {
    phone: '9876500001',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Priyanjali',
    lastName: 'Chawla',
    dob: new Date('2000-06-15'),
    height: "5'5\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'MS in HCI, Georgia Tech',
    profession: 'Senior Product Designer',
    professionSector: 'Corporate Job',
    company: 'Apple Inc.',
    location: 'Mumbai, Maharashtra',
    bio: 'Design enthusiast who loves minimalism, traveling to Nordic countries, and standard filter coffees. Believes in balancing Sindhi heritage with progressive global views.',
    compatibilityScore: 98,
    initials: 'PC',
    fathersOccupation: 'Real Estate Developer',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#E0C3FC', '#8EC5FC'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1']
  },
  {
    phone: '9876500002',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Ritik',
    lastName: 'Lalwani',
    dob: new Date('1998-04-12'),
    height: "5'11\"",
    city: 'Bangalore',
    state: 'Karnataka',
    maritalStatus: 'Never Married',
    education: 'B.Tech, IIT Bombay',
    profession: 'Co-Founder & CEO',
    professionSector: 'Business',
    company: 'Fintech Unicorn',
    location: 'Bangalore, Karnataka',
    bio: 'Building systems to democratize credit in India. Passionate about scaling startups, writing tech blogs, and playing classical piano. Looking for a partner who is driven and empathetic.',
    compatibilityScore: 95,
    initials: 'RL',
    fathersOccupation: 'Retired Textile Merchant',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#FEE140', '#FA709A'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500003',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Hiteshi',
    lastName: 'Sadhwani',
    dob: new Date('1999-09-20'),
    height: "5'6\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'MBA, ISB Hyderabad',
    profession: 'Investment Banking Associate',
    professionSector: 'Corporate Job',
    company: 'Goldman Sachs',
    location: 'Mumbai, Maharashtra',
    bio: 'Analyzes markets by day, paints abstract art by night. Love exploring boutique cafes in Dubai and reading philosophy. Looking for a sincere companion to build a beautiful life.',
    compatibilityScore: 92,
    initials: 'HS',
    fathersOccupation: 'Diamond Merchant',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#43E97B', '#38F9D7'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500004',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Karan',
    lastName: 'Gidwani',
    dob: new Date('1997-12-05'),
    height: "6'0\"",
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Never Married',
    education: 'MS in CS, Stanford University',
    profession: 'Software Architect',
    professionSector: 'Corporate Job',
    company: 'Google LLC',
    location: 'Ahmedabad, Gujarat',
    bio: 'AI researcher and open-source contributor. Weekend runner and trekker. Looking for someone with a scientific temperament, a warm heart, and a love for deep conversations.',
    compatibilityScore: 90,
    initials: 'KG',
    fathersOccupation: 'Senior Cardiologist',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#FA8BFF', '#2BD2FF', '#2BFF88'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1']
  },
  {
    phone: '9876500005',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Mehak',
    lastName: 'Vaswani',
    dob: new Date('2001-01-30'),
    height: "5'4\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'MD, KEM Hospital Mumbai',
    profession: 'Pediatric Resident',
    professionSector: 'Corporate Job',
    company: 'Lilavati Hospital',
    location: 'Mumbai, Maharashtra',
    bio: 'Dedicated to children\'s healthcare. Enjoys gardening, baking artisanal sourdoughs, and family gatherings. Looking for a family-oriented, kind-hearted gentleman.',
    compatibilityScore: 88,
    initials: 'MV',
    fathersOccupation: 'Industrialist (Chemicals)',
    incomeBracket: '10-20 Lakhs',
    gradientColors: ['#FFFF9A', '#FECFEF'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500006',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Varun',
    lastName: 'Mulchandani',
    dob: new Date('1996-03-24'),
    height: "5'9\"",
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Never Married',
    education: 'B.Sc in Economics, Wharton School',
    profession: 'VP of Real Estate',
    professionSector: 'Business',
    company: 'Mulchandani Group',
    location: 'Ahmedabad, Gujarat',
    bio: 'Oversees asset portfolios. Passionate about architecture, sailing, and golf. Believes that mutual respect and shared laughter are the pillars of a long-lasting marriage.',
    compatibilityScore: 85,
    initials: 'VM',
    fathersOccupation: 'Chairman, Mulchandani Group',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#F6D365', '#FDA085'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500007',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Payal',
    lastName: 'Kukreja',
    dob: new Date('2002-05-18'),
    height: "5'3\"",
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Never Married',
    education: 'B.Des, NID Ahmedabad',
    profession: 'Creative Director',
    professionSector: 'Business',
    company: 'Studio Kukreja',
    location: 'Ahmedabad, Gujarat',
    bio: 'Visual storyteller and luxury brand designer. Love street photography and filter coffee. Seeking a partner who is passionate about art, travel, and cultural heritage.',
    compatibilityScore: 94,
    initials: 'PK',
    fathersOccupation: 'Textile Factory Owner',
    incomeBracket: '10-20 Lakhs',
    gradientColors: ['#A1C4FD', '#C2E9FB'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1', 'uploaded_photo_2']
  },
  {
    phone: '9876500008',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Devansh',
    lastName: 'Hingorani',
    dob: new Date('1997-08-11'),
    height: "5'10\"",
    city: 'Delhi NCR',
    state: 'Delhi',
    maritalStatus: 'Never Married',
    education: 'MBA, IIM Ahmedabad',
    profession: 'Senior Consultant',
    professionSector: 'Corporate Job',
    company: 'McKinsey & Co',
    location: 'Delhi NCR',
    bio: 'Management consultant focusing on corporate strategy. Loves reading history books and playing badminton. Looking for an independent, smart, and career-driven partner.',
    compatibilityScore: 91,
    initials: 'DH',
    fathersOccupation: 'IAS Officer',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#D4FC79', '#96E6A1'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500009',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Suhana',
    lastName: 'Relwani',
    dob: new Date('2000-02-28'),
    height: "5'7\"",
    city: 'Pune',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'MA in Psychology, DU',
    profession: 'Clinical Psychologist',
    professionSector: 'Corporate Job',
    company: 'MindCare Clinic',
    location: 'Pune, Maharashtra',
    bio: 'Mental health advocate. Enjoys practicing yoga, playing tennis, and exploring offbeat hill stations. Looking for a partner who is empathetic, mature, and good listener.',
    compatibilityScore: 89,
    initials: 'SR',
    fathersOccupation: 'Senior Advocate, High Court',
    incomeBracket: '5-10 Lakhs',
    gradientColors: ['#FAD0C4', '#FFD1FF'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500010',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Anish',
    lastName: 'Makhija',
    dob: new Date('1999-11-05'),
    height: "5'8\"",
    city: 'Jaipur',
    state: 'Rajasthan',
    maritalStatus: 'Never Married',
    education: 'B.Sc in Hospitality, Cornell University',
    profession: 'Hotel General Manager',
    professionSector: 'Business',
    company: 'Makhija Residency',
    location: 'Jaipur, Rajasthan',
    bio: 'Managing family luxury boutique hotels. Passionate about food science, travel, and hosting culinary experiences. Looking for a warm, family-oriented partner.',
    compatibilityScore: 87,
    initials: 'AM',
    fathersOccupation: 'Hotelier',
    incomeBracket: '10-20 Lakhs',
    gradientColors: ['#FDA085', '#F6D365'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500011',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Drishti',
    lastName: 'Bathija',
    dob: new Date('2001-05-14'),
    height: "5'2\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'B.Com, HR College Mumbai',
    profession: 'Not Working',
    professionSector: 'Not Working',
    company: 'None',
    location: 'Mumbai, Maharashtra',
    bio: 'Homemaker by interest, painter by choice. Enjoys cooking traditional Sindhi cuisines like Kadhi Chawal and managing family archives. Looking for a respectful, established merchant partner.',
    compatibilityScore: 83,
    initials: 'DB',
    fathersOccupation: 'Retired Jeweller',
    incomeBracket: 'Under 5 Lakh',
    gradientColors: ['#FF9A9E', '#FECFEF'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500012',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Jatin',
    lastName: 'Chawla',
    dob: new Date('1995-10-18'),
    height: "5'11\"",
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Never Married',
    education: 'MBA, London Business School',
    profession: 'Director of Operations',
    professionSector: 'Business',
    company: 'Chawla Logistics',
    location: 'Ahmedabad, Gujarat',
    bio: 'Expanding logistics network in western India. Enjoys golf and collecting vintage wristwatches. Looking for an educated, modern partner ready to settle in Gujarat.',
    compatibilityScore: 86,
    initials: 'JC',
    fathersOccupation: 'Founder, Chawla Logistics',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#C2E9FB', '#A1C4FD'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1']
  },
  {
    phone: '9876500013',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Kavita',
    lastName: 'Mahtani',
    dob: new Date('1999-07-04'),
    height: "5'6\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'B.Des, NIFT Mumbai',
    profession: 'Fashion Director',
    professionSector: 'Business',
    company: 'Mahtani Couture',
    location: 'Mumbai, Maharashtra',
    bio: 'Bridal wear designer. Passionate about classical Indian music, handloom fabrics, and visiting antique markets in Paris. Looking for an artistic and respectful partner.',
    compatibilityScore: 97,
    initials: 'KM',
    fathersOccupation: 'Textile Exporter',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#FF9A9E', '#FECFEF'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500014',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Rohan',
    lastName: 'Jagtiani',
    dob: new Date('1996-08-30'),
    height: "6'1\"",
    city: 'Bangalore',
    state: 'Karnataka',
    maritalStatus: 'Never Married',
    education: 'PhD in Machine Learning, Carnegie Mellon',
    profession: 'Lead AI Researcher',
    professionSector: 'Corporate Job',
    company: 'Anthropic AI',
    location: 'Bangalore, Karnataka',
    bio: 'Working on safety alignments for large language models. Likes playing chess, hiking in the Western Ghats, and brewing pour-overs. Looking for an intellectually curious partner.',
    compatibilityScore: 94,
    initials: 'RJ',
    fathersOccupation: 'Senior Bureaucrat (IAS)',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#84FAB0', '#8FD3F4'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1']
  },
  {
    phone: '9876500015',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Simran',
    lastName: 'Jaisinghani',
    dob: new Date('2001-09-25'),
    height: "5'4\"",
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Never Married',
    education: 'BBA, FLAME University Pune',
    profession: 'Luxury Wedding Planner',
    professionSector: 'Business',
    company: 'The Grand Events',
    location: 'Ahmedabad, Gujarat',
    bio: 'Curating royal destination weddings across India. Loves baking, reading historical fiction, and tennis. Seeking a warm, family-oriented partner with a good sense of humor.',
    compatibilityScore: 91,
    initials: 'SJ',
    fathersOccupation: 'Hotelier (Hotel Chain Owner)',
    incomeBracket: '10-20 Lakhs',
    gradientColors: ['#A18CD1', '#FBC2EB'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500016',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Sanjay',
    lastName: 'Kukreja',
    dob: new Date('1997-10-09'),
    height: "5'9\"",
    city: 'Dubai',
    state: 'UAE',
    maritalStatus: 'Never Married',
    education: 'MBA, Wharton School',
    profession: 'Private Equity Vice President',
    professionSector: 'Corporate Job',
    company: 'Mubadala Capital',
    location: 'Dubai, UAE',
    bio: 'Investing in tech startups across EMEA. Avid scuba diver and squash player. Looking for a partner who is career-driven, independent, and values Sindhi family traditions.',
    compatibilityScore: 96,
    initials: 'SK',
    fathersOccupation: 'Jeweller (Dubai Gold Souk)',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#FAD0C4', '#FFD1FF'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1']
  },
  {
    phone: '9876500017',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Neha',
    lastName: 'Lalla',
    dob: new Date('2000-06-26'),
    height: "5'5\"",
    city: 'Pune',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'MDS, KGMU Lucknow',
    profession: 'Pediatric Dentist',
    professionSector: 'Professional',
    company: 'Lalla Dental Clinic',
    location: 'Pune, Maharashtra',
    bio: 'Dentist specialized in children. Enjoys volunteering at NGO camps, writing poetry, and practicing Vipassana. Looking for a compassionate and self-aware partner.',
    compatibilityScore: 89,
    initials: 'NL',
    fathersOccupation: 'Real Estate Developer',
    incomeBracket: '10-20 Lakhs',
    gradientColors: ['#FFD1FF', '#FDA085'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500018',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Rahul',
    lastName: 'Punwani',
    dob: new Date('1998-03-28'),
    height: "5'11\"",
    city: 'Bangalore',
    state: 'Karnataka',
    maritalStatus: 'Never Married',
    education: 'M.Tech, IISc Bangalore',
    profession: 'Staff Software Engineer',
    professionSector: 'Corporate Job',
    company: 'Netflix Inc.',
    location: 'Bangalore, Karnataka',
    bio: 'Scaling streaming infrastructure globally. Enjoys guitar jamming, reading sci-fi books, and marathon running. Seeking an educated, progressive partner ready to explore life.',
    compatibilityScore: 93,
    initials: 'RP',
    fathersOccupation: 'Retired Chief Justice',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#C2E9FB', '#A1C4FD'],
    uploadedPhotos: ['uploaded_photo_0']
  },
  {
    phone: '9876500019',
    profileFor: 'Self',
    gender: 'Female',
    firstName: 'Payal',
    lastName: 'Gurnani',
    dob: new Date('1999-05-27'),
    height: "5'7\"",
    city: 'Jaipur',
    state: 'Rajasthan',
    maritalStatus: 'Never Married',
    education: 'B.Sc in Hospitality, Cornell University',
    profession: 'Director of Operations',
    professionSector: 'Business',
    company: 'Heritage Palaces',
    location: 'Jaipur, Rajasthan',
    bio: 'Restoring and managing heritage Havelis in Rajasthan. Loves horse riding, photography, and Rajasthani history. Seeking an established entrepreneur partner.',
    compatibilityScore: 95,
    initials: 'PG',
    fathersOccupation: 'Heritage Hotel Owner',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#F6D365', '#FDA085'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1', 'uploaded_photo_2']
  },
  {
    phone: '9876500020',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Sanjay',
    lastName: 'Wadhwani',
    dob: new Date('1995-12-15'),
    height: "6'0\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'B.Sc in Finance, NYU Stern',
    profession: 'Managing Director',
    professionSector: 'Business',
    company: 'Wadhwani Capital',
    location: 'Mumbai, Maharashtra',
    bio: 'Managing private wealth and mid-market equities. Yacht owner and golf enthusiast. Believes in building a life of growth, travel, and mutual respect.',
    compatibilityScore: 98,
    initials: 'AW',
    fathersOccupation: 'Industrialist (Steel)',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#FA8BFF', '#2BD2FF'],
    uploadedPhotos: ['uploaded_photo_0', 'uploaded_photo_1']
  },
  {
    phone: '9413879444',
    profileFor: 'Self',
    gender: 'Male',
    firstName: 'Piyush',
    lastName: 'Wadhwani',
    dob: new Date('1998-06-15'),
    height: "5'11\"",
    city: 'Mumbai',
    state: 'Maharashtra',
    maritalStatus: 'Never Married',
    education: 'B.Tech, IIT Bombay',
    profession: 'Software Architect',
    company: 'Apple',
    location: 'Mumbai, Maharashtra',
    bio: 'Building tech and designs for premium platforms.',
    compatibilityScore: 100,
    initials: 'PW',
    fathersOccupation: 'Business owner',
    incomeBracket: '20+ Lakhs',
    gradientColors: ['#C2E9FB', '#A1C4FD'],
    uploadedPhotos: ['uploaded_photo_0']
  }
];

async function seedDatabase() {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      throw new Error('MONGO_URI is missing from backend environment variables.');
    }
    
    console.log('[Seeding] Connecting to MongoDB Atlas cluster...');
    await mongoose.connect(mongoUri);
    console.log('[Seeding] Connected successfully.');

    // 1. Delete existing collection data
    console.log('[Seeding] Clearing existing User and Interest collections...');
    await User.deleteMany({});
    await Interest.deleteMany({});
    console.log('[Seeding] Collections cleared.');

    // 2. Filter out test profile and enrich remaining profiles with email and caste fields
    const finalProfilesToSeed = seedProfiles
      .filter(p => p.phone !== '9413879444')
      .map(p => ({
        ...p,
        email: `${p.firstName.toLowerCase()}.${p.lastName.toLowerCase()}@example.com`,
        caste: p.lastName
      }));

    console.log(`[Seeding] Seeding ${finalProfilesToSeed.length} profiles...`);
    const createdUsers = await User.insertMany(finalProfilesToSeed);
    console.log(`[Seeding] Successfully seeded ${createdUsers.length} profiles.`);

    await mongoose.disconnect();
    console.log('[Seeding] Database connection closed.');
    process.exit(0);
  } catch (error) {
    console.error('[Seeding Error] Seeding process failed:', error.message);
    process.exit(1);
  }
}

seedDatabase();
